### ISSUE TITLE
Ability to retreive CAPEC IDs

### ISSUE THREAD

**Issue by Voronsky** [OTRF/ATTACK-Python-Client#1]
Hello Cyb3rWard0g,

 Was referred to check this repo out as I was using the MITRE ATT&CK Wiki and I've found your tool to be awesome thus far!

 Quick question, I know this is in Beta, but are there any plans to add functionality to be able to grab CAPEC IDs of specific softwares? Currently I can grab all their various Technique IDs, but I'm not sure where or what I need to call, to grab CAPEC ID of any software I query about. As it stands, the MITRE Wiki provides CAPEC IDs for each software in their Software List, so I'm looking into how to get that via your python module.

Thanks!

**Comment by Cyb3rWard0g** [comment]
Hey @Voronsky ! Yes I will add that to the to-do list. I forgot to add it there. The plan was to start with only Enterprise ATT&CK, but I ended up working on the other ones (PRE & Mobile) 👍  I will close this issue when I add CAPEC. Thank you @Voronsky

**Comment by Cyb3rWard0g** [comment]
Hey @Voronsky , I dont think this can be done yet. I checked again the collections available from the TAXII server and CAPEC is not available yet
```
>>> from stix2 import TAXIICollectionSource
>>> from taxii2client import Server
>>> 
>>> # Instantiate server and get API Root
... server = Server("https://cti-taxii.mitre.org/taxii/")
>>> api_root = server.api_roots[0]
>>> for collection in api_root.collections:
...           print(collection.title + ": " + collection.id)
... 
Enterprise ATT&CK: 95ecc380-afe9-11e4-9b6c-751b66dd541e
PRE-ATT&CK: 062767bd-02d2-4b72-84ba-56caef0f8658
Mobile ATT&CK: 2f669986-b40b-4423-b720-4396ca6a462b
```

**Comment by Voronsky** [comment]
@Cyb3rWard0g  thank you for the response. Do you think perhaps, all SDOs will contain the capecs as an an SDO property of `external_references` ? [Reference Here](https://stix2.readthedocs.io/en/latest/api/stix2.v20.sdo.html). 

That is, can we expect to find CAPECs within that property, so that when we grab an SDO from any of those collections via TAXII, bundled in the sdo's `external_references` capecs would be listed there as well?

**Comment by Cyb3rWard0g** [comment]
HEy @Voronsky , CAPECs inside of external_references. I dont think it will be done that way. CTI already has CAPEC objects in STIX format https://github.com/mitre/cti/tree/master/capec  However, as I showed above, they are not available via TAXII yet. I will open a question in the ATT&CK CTI repo

**Comment by Cyb3rWard0g** [comment]
@Voronsky can you show me an example where you see CAPEC Ids in a Software List??

**Comment by Voronsky** [comment]
@Cyb3rWard0g  sorry I definitely missed a chunk here in my original description. CAPEC IDs are not directly referenced in a Software List, but rather when you grab any Software from that list, and look at the techniques. MITRE's wiki has some mapped to a CAPEC, and it can be found using this API currently

```https://attack.mitre.org/wiki/Property:Has_CAPEC_ID``` via browser or

```[[Category:Technique]][[Has ID::{}]]|?Has CAPEC ID``` .

So currently as it stands, I use the wiki API to grab a software in the Software list, then grab it's technique, and check which ones have a CAPEC ID and what it is. So I was wondering if in this up and coming rewrite, is there is a way to grab an SDO, their known techniques and if there was a key with a list of CAPECs associated to each Technique or something of that sort bundled in these collections.

If not, then it's fine! 

Thank you for swift correspondence.

**Comment by Cyb3rWard0g** [comment]
Ohh okayy!! Nice I remember that from the WIkiAPI yes. Yeah I havent seen relationships defined with CAPEC IDs. I will wait and see when that is available then 👍 I will leave this open until it is possible and I add it to the script 😄

**Comment by Cyb3rWard0g** [comment]
Hey @Voronsky , 
I hope you are having a good day. Check the latest updated to the library. It has CAPEC IDs mapped to techniques now. let me know if this is what you were looking for. Thank you.
