### ISSUE TITLE
Failed to pass a STIX object (to another function) that was retrieved by get_object_by_attack_id() and get_group_by_alias()

### ISSUE THREAD

**Issue by sahar55** [OTRF/ATTACK-Python-Client#20]
Hey Roberto, 
I found few small things that seems like issues (it's also possible I don't yet know how to use this lib properly tho).
my scenario is that I wanted to retrieve a singular STIX object and pass it to another function to do its magic.
desired flow: 
 `fin7_obj = client.get_object_by_attack_id('intrusion-set', 'G0046')`
`client.get_techniques_used_by_group(fin7_obj)`

However I received the following error:
`if stix_object['type'] == 'course-of-action':
TypeError: list indices must be integers or slices, not str`

Looking at the type of object I received from both get_object_by_attack_id() and get_group_by_alias(), it seems that they are retrieved as a list, where the client.get_techniques_used_by_group() expects a 'dict' 

And another small issue is that  get_group_by_alias() is case sensitive, meaning:
`get_group_by_alias('fin7')`  - Wouldn't work
`get_group_by_alias('FIN7')`  - Would work

Let me know if you need more info, or if i'm just not using this correctly please :D 
Have a great day, Sahar

**Comment by Cyb3rWard0g** [comment]
Hello @sahar55 !

Sorry for the delay. I meant to share this sooner. The first question is that the function `get_techniques_used_by_group` expects 1 STIX object. However, `get_object_by_attack_id` returns a list. Therefore, you just have to refer to the only first object in the the `fin7_obj` list. 

![image](https://user-images.githubusercontent.com/9653181/118218402-54009700-b445-11eb-9e4f-94009af6a1be.png)

code:
```
from attackcti import attack_client
lift = attack_client()

fin7_obj = lift.get_object_by_attack_id('intrusion-set', 'G0046')
techniques = lift.get_techniques_used_by_group(fin7_obj[0])  
```

The second small issue should be a feature request. I will take that in consideration for the next PR. Thank you @sahar55 !
