### ISSUE TITLE
Add API for ICS domain

### ISSUE THREAD

**Issue by isaisabel** [OTRF/ATTACK-Python-Client#21]
As a user of ATT&CK Python Client, I would like to be able to access STIX data for the _ATT&CK for ICS_ domain using this library. Ideally, functions similar to those implement for Enterprise, Pre-ATT&CK and Mobile would be developed for accessing ICS data.

[ATT&CK v8](https://github.com/mitre/cti/releases/tag/ATT%26CK-v8.1) added of STIX data for the ICS domain. This can be accessed via [the MITRE/CTI GitHub repository](https://github.com/mitre/cti) in the `ics-attack` folder, or using the official ATT&CK TAXII server via collection ID `02c3ef24-9cd4-48f3-a99f-b74ce24f1d34`.

The ATT&CK for ICS domain has roughly the same data formatting as the Enterprise domain. [The MITRE/CTI USAGE document explains the data model in more detail](https://github.com/mitre/cti/blob/master/USAGE.md#the-attck-data-model).

**Comment by Cyb3rWard0g** [comment]
Thank you Isabel! I released a new version of attackcti to handle ICS 😄  . I appreciate you reaching out and providing additional information

https://pypi.org/project/attackcti/
