### ISSUE TITLE
Remove pre-ATT&CK or mark it as deprecated in the documentation

### ISSUE THREAD

**Issue by isaisabel** [OTRF/ATTACK-Python-Client#22]
[ATT&CK version 8](https://attack.mitre.org/resources/updates/updates-october-2020/index.html) migrated the pre-ATT&CK domain into a set of new tactics under the Enterprise domain. While the ATT&CK team will be keeping the STIX data for pre-ATT&CK available in order to avoid breaking any potential user automation, all data in the pre-ATT&CK domain has been marked with the `x_mitre_deprecated` tag, and all object `description` fields have been modified to note the migration. See [the documentation on MITRE/CTI](https://github.com/mitre/cti/tree/master/pre-attack) for more details.

It would be desirable for this tool to also reflect this change to encourage users to discontinue use of the old pre-ATT&CK dataset. However, removing the pre-ATT&CK API could potentially cause problems for users with automation relying on those functions. Several alternative ways to document the removal might be:
- marking those functions as deprecated on readthedocs
- printing warnings to stdout when the relevant functions are used
- Removing the functions from the documentation but keeping them in the codebase
- some combination of the above

**Comment by Cyb3rWard0g** [comment]
Thank you very much Isabel for sharing some of the alternatives to handle the deprecation of PRE ATT&CK. I have updated it in the main page of README and in the code (comments). I believe I could add the warnings to stout as you propose. Thank you for the suggestions once again

**Comment by Cyb3rWard0g** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/9653181/100158337-033ab900-2e7a-11eb-8a4f-4dbf8697ee9e.png">

😉 

https://pypi.org/project/attackcti/
