### ISSUE TITLE
get_software_used_by_group returns all tools for groups with no actual tools/ software

### ISSUE THREAD

**Issue by osV22** [OTRF/ATTACK-Python-Client#27]
Hello Roberto,

When getting all the software/ tools used by a group, there is an issue with groups that have no software listed.
The result is getting all 605 tools listed for those groups that have no actual software listed on the site.

Example: 
```
groups = lift.get_groups()
one_group = groups[40] # FIN4/ G0085
group_software = lift.get_software_used_by_group(one_group) # returns all 605 tools
```

[MITRE's site ](https://attack.mitre.org/groups/G0085/) does not list any software for the group. 
This is also the case with groups such as "APT34" (67) which is just an alias to "OilRig" (73/ G0049) which has the actual tools listed.  Groups with the same issue include [2, 8, 20, 40, 41, 61, 67].

Possible reference: [all_software_list](https://github.com/OTRF/ATTACK-Python-Client/blob/3fead0ead85a1d076c7b5a3ffd67bdc9b4497eb8/attackcti/attack_api.py#L1202)

Apologies in advance if this was done by design which I know can be omitted if we choose to. I tried MITRE's live cti server to confirm this and indeed they did not list the tools or the group either if they had no software/ tools.

**Comment by beerMT** [comment]
+1 I am getting the same behavior

**Comment by Cyb3rWard0g** [comment]
Hello @osV22 !

I think I know what is going on 😱 ! The FILTER method from stix2 when the filter returns zero and it is part of a multiple filters query, it treats the filters as OR statements and not AND statements.

This is the filter in this function

```
relationships = self.get_relationships_by_object(stix_object)
        software_relationships = list()
        for relation in relationships:
            if get_type_from_id(relation.target_ref) in ['malware', 'tool']:
                software_relationships.append(relation)
        filter_objects = [
            Filter('type', 'in', ['malware', 'tool']),
            Filter('id', '=', [r.target_ref for r in software_relationships])
        ]
```

As you can see in the filters above, I look for `ALL` malware or tools that have the `RELATIONSHIP` id as a target reference equal to `RELATIONSHIPS` that belong to the `GROUP` object. 

However, while looking at all the relationships of the GROUP FIN4, I only see objects of type `ATTACK PATTERN` -> `TECHNIQUE`

```
>>> for relation in relationships:
...     get_type_from_id(relation.target_ref):
... 
'attack-pattern'
'attack-pattern'
'attack-pattern'
'attack-pattern'
'attack-pattern'
'attack-pattern'
'attack-pattern'
'attack-pattern'
'attack-pattern'
'attack-pattern'
'attack-pattern'
'attack-pattern'
```

Therefore, it seems that when the `FILTER` returns a null expression or it is empty, it is not used at all. Since we have two filters (MALWARE/TOOLS + RELATIONSHIPS IDs) but the relationships one is empty, then it returns all `MALWARE` and `TOOLS`.

**Comment by Cyb3rWard0g** [comment]
Fixing it now and pushing a hotfix soon.

**Comment by Cyb3rWard0g** [comment]
Added a quick fix in my lab and it seems to work now

![image](https://user-images.githubusercontent.com/9653181/124349001-07bb1300-dbbb-11eb-9844-f7e23ccf95fd.png)

I tried it with a different group and it seems to be working fine. There were similar loops in other functions, so I fixed those too.

Group: https://attack.mitre.org/groups/G0120

![image](https://user-images.githubusercontent.com/9653181/124349051-3fc25600-dbbb-11eb-9233-a6b829cdc9b7.png)


![image](https://user-images.githubusercontent.com/9653181/124349081-5cf72480-dbbb-11eb-99b4-f424376f3028.png)

**Comment by Cyb3rWard0g** [comment]
I tested it with groups `2, 8, 20, 40, 41, 61, 67`

![image](https://user-images.githubusercontent.com/9653181/124349147-c9722380-dbbb-11eb-9f46-5b5f99f5fba9.png)

However, group 61 (https://attack.mitre.org/groups/G0066/)  does have `SOFTWARE`: 

9 SOFTWARE

![image](https://user-images.githubusercontent.com/9653181/124349178-f4f50e00-dbbb-11eb-86a7-256f13b1de0d.png)

![image](https://user-images.githubusercontent.com/9653181/124349240-2c63ba80-dbbc-11eb-825c-fee648589bf1.png)

![image](https://user-images.githubusercontent.com/9653181/124349205-0ccc9200-dbbc-11eb-9c82-701c408ae8e6.png)

**Comment by Cyb3rWard0g** [comment]
I updated the library to version 0.3.4.4

https://pypi.org/project/attackcti/

![image](https://user-images.githubusercontent.com/9653181/124349637-1e169e00-dbbe-11eb-80ad-9a0bae1ed8cd.png)

it seems to be working fine now :) Thank you very much @osV22 and @beerMT ! Enjoy your weekend!

**Comment by beerMT** [comment]
Nicely done, thanks for jumping on that. Cheers!
