### ISSUE TITLE
specify and update README.md file and requirements section

### ISSUE THREAD

**Issue by thegautamkumarjaiswal** [OTRF/ATTACK-Python-Client#28]

**Comment by Cyb3rWard0g** [comment]
Thank you @thegautamkumarjaiswal ! I added some comments to your PR. I appreciate you taking the time to contribute to the project! :)

**Comment by Cyb3rWard0g** [comment]
Thank you again for taking the time @thegautamkumarjaiswal ! Enjoy your weekend.

**Comment by thegautamkumarjaiswal** [comment]
@Cyb3rWard0g Thank you and your project to giving me great opportunity.
