### ISSUE TITLE
AttributeError: module 'pandas' has no attribute 'json_normalize'

### ISSUE THREAD

**Issue by bobsyourmom** [OTRF/ATTACK-Python-Client#36]
When running the df.reindex output, using your python commands as a script, I received the error above.

the fix was to add this line to the imports at the top of the script:

from pandas.io.json import json_normalize

ref:
https://stackoverflow.com/questions/61336238/getting-attributeerror-module-pandas-has-no-attribute-json-normalize-while

**Comment by Cyb3rWard0g** [comment]
Hello @bobsyourmom ! Would you mind sharing how you are using the library again? Please and thank you!

**Comment by MrAsimZahid** [comment]
Hi @bobsyourmom,

Check the notebook below for usage of json_normalize.

```python
from pandas as pd
pd.json_normalize(json_list)
```
I hope it will be helpful.
Thank you. 

https://www.kaggle.com/asimzahid/read-and-normalize-nested-json-data
