### ISSUE TITLE
TAXII service returns incomplete data when run in Github actions

### ISSUE THREAD

**Issue by Neo23x0** [OTRF/ATTACK-Python-Client#43]
In the test used in our Sigma project, we've noticed that results returned from the TAXII service seem incomplete when data is retrieved in a Github workflow. 

https://github.com/SigmaHQ/sigma/runs/4868994244?check_suite_focus=true#step:5:17

I've added a line that outputs the length of different lists and it differs when run locally and in a Github workflow. This seems to be the reason why our tests fail. Many MITRE ATT&CK techniques cannot be found in these incomplete lists. 

```
from attackcti import attack_client

def get_mitre_data():
    """
    Generate tags from live TAXI service to get up-to-date data
    """
    # Get ATT&CK information
    lift = attack_client()
    # Techniques
    MITRE_TECHNIQUES = []
    MITRE_TECHNIQUE_NAMES = []
    MITRE_PHASE_NAMES = set()
    MITRE_TOOLS = []
    MITRE_GROUPS = []
    # Techniques 
    enterprise_techniques = lift.get_enterprise_techniques()
    for t in enterprise_techniques:
        MITRE_TECHNIQUE_NAMES.append(t['name'].lower().replace(' ', '_').replace('-', '_'))
        for r in t.external_references:
            if 'external_id' in r:
                MITRE_TECHNIQUES.append(r['external_id'].lower())
        if 'kill_chain_phases' in t:
            for kc in t['kill_chain_phases']:
                if 'phase_name' in kc:
                    MITRE_PHASE_NAMES.add(kc['phase_name'].replace('-','_'))
    # Tools / Malware
    enterprise_tools = lift.get_enterprise_tools()
    for t in enterprise_tools:
        for r in t.external_references:
            if 'external_id' in r:
                MITRE_TOOLS.append(r['external_id'].lower())
    enterprise_malware = lift.get_enterprise_malware()
    for m in enterprise_malware:
        for r in m.external_references:
            if 'external_id' in r:
                MITRE_TOOLS.append(r['external_id'].lower())
    # Groups
    enterprise_groups = lift.get_enterprise_groups()
    for g in enterprise_groups:
        for r in g.external_references:
            if 'external_id' in r:
                MITRE_GROUPS.append(r['external_id'].lower())

    # Debugging 
    print("MITRE ATT&CK LIST LENGTHS: %d %d %d %d %d" % (len(MITRE_TECHNIQUES), len(MITRE_TECHNIQUE_NAMES), len(list(MITRE_PHASE_NAMES)), len(MITRE_GROUPS), len(MITRE_TOOLS)))
```
You can find the full test script here: https://github.com/SigmaHQ/sigma/blob/rule-devel/tests/test_rules.py

![Screenshot 2022-01-19 at 15 33 34](https://user-images.githubusercontent.com/2851492/150151792-f7697258-986b-43b6-9d88-1a118af2d5f0.png)

Do you have any idea what could cause this error?

**Comment by Cyb3rWard0g** [comment]
Hello @Neo23x0!

I can see you are using maybe the latest version of attackcti? Also, can you provide the version for stix and taxii client? There was a bug that was fixed recently related to incomplete results.

https://github.com/OTRF/ATTACK-Python-Client/blob/master/requirements.txt

bug already patched in TAXII client: https://github.com/oasis-open/cti-taxii-client/issues/104

Also, something that we added recently to the library is a way to remove revoked and deprecated techniques. That is turned on by default in the latest release. I believe your GitHub actions runs latest version right?

Also, regarding the WARNING messages, that is also something that was added to the TAXII client library. The library by itself handles pagination and those messages should just be ignored. ATT&CK TAXII Server does not set the `Content-Range` header. 

```
[taxii2client.v20] [WARNING ] [2022-01-19 14:26:14,559] TAXII Server Response with different amount of objects! Setting per_request=474
[taxii2client.v20] [WARNING ] [2022-01-19 14:26:14,867] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2022-01-19 14:26:14,871] TAXII Server Response with different amount of objects! Setting per_request=133
```

Let me take a look at your script. I am working on this library today so I will update this issue as soon as I can.

**Comment by Cyb3rWard0g** [comment]
I ran your initial script locally and I got the same results as your GitHub actions:

![image](https://user-images.githubusercontent.com/9653181/150163878-a5741a5e-8779-4b77-92f3-863c98fa3131.png)

Number of techniques: 

Something I noticed in your initial image was the number of techniques: 707 . That number makes sense if we consider `deprecated` and `revoked` techniques. For example, if I run the following code without removing revoked or deprecated, I get 707 techniques from `enterprise`:

![image](https://user-images.githubusercontent.com/9653181/150164468-43762abb-674b-4e4b-99aa-f11a4ecc3442.png)

As I mentioned before, we recently added a function to remove `deprecated` and `revoked` by default:

https://github.com/OTRF/ATTACK-Python-Client/blob/master/attackcti/attack_api.py#L283-L290

You can include deprecated and revoked by setting the parameter `skip_revoked_deprecated` to `False` when running the `get_enterprise_techniques` and other functions:

https://github.com/OTRF/ATTACK-Python-Client/blob/master/attackcti/attack_api.py#L342-L371

**Comment by Cyb3rWard0g** [comment]
I am now checking the following tags:

![image](https://user-images.githubusercontent.com/9653181/150165240-df5043e2-7949-4001-a859-d979bf881801.png)

**Comment by Cyb3rWard0g** [comment]
oh btw forgot to add the code to test direct interaction with TAXII to validate that `707` was the number of techniques without removing deprecated or revoked:

```python
from stix2 import TAXIICollectionSource, Filter
from taxii2client.v20 import Collection

ATTACK_STIX_COLLECTIONS = "https://cti-taxii.mitre.org/stix/collections/"
ENTERPRISE_ATTACK = "95ecc380-afe9-11e4-9b6c-751b66dd541e"
ENTERPRISE_ATTACK_LOCAL_DIR = "enterprise-attack"

ENTERPRISE_COLLECTION = Collection(ATTACK_STIX_COLLECTIONS + ENTERPRISE_ATTACK + "/")
TC_ENTERPRISE_SOURCE = TAXIICollectionSource(ENTERPRISE_COLLECTION)

techniques = TC_ENTERPRISE_SOURCE.query(Filter("type", "=", "attack-pattern"))
len(techniques)
```

just in case for future references :)

**Comment by Neo23x0** [comment]
Thanks for the quick reply. I think, we'll work on the deprecated techniques and remove them from our rules in a big PR. 
Most users won't use them anymore anyways.

**Comment by Neo23x0** [comment]
@frack113 is already on it

**Comment by Neo23x0** [comment]
Thanks for your help

**Comment by Cyb3rWard0g** [comment]
Not a problem @Neo23x0 ! Happy to help. I just validated one of the technique numbers being tagged and not present in the total number of techniques without `deprecated` or `revoked` and that's what it is :

![image](https://user-images.githubusercontent.com/9653181/150166648-90efe723-21b7-420b-a237-8a72447e0ba9.png)

Once again, for now, what you can do is set the parameter `skip_revoked_deprecated=False` when running the `get_enterprise_techniques` function :) Keep me posted!

Hey @frack113! Let me know if you have any other question while working on the deprecated techniques.

**Comment by frack113** [comment]
The fix was simple but painful to do by hand the 497 files.
If you have a func in the API to convert deprecated  to new techniques , next time I make a python script 😄

**Comment by Cyb3rWard0g** [comment]
what was the fix on your end? @frack113

**Comment by frack113** [comment]
In the rules, I remove the deprecated techniques and add the new one if needed

**Comment by Cyb3rWard0g** [comment]
oh wow! that's a lot! Is that part of the PR that you guys are pushing for Sigma to make all those changes to all rules? 

Let me know if I can close this issue. Thank you!

**Comment by Neo23x0** [comment]
Yes, thanks. @frack113 fixed it with this pull request that changed 497 files. 😄

https://github.com/SigmaHQ/sigma/pull/2576
