### ISSUE TITLE
Error: AttributeError: 'attack_client' object has no attribute 'remove_revoked'

### ISSUE THREAD

**Issue by pendraggon87** [OTRF/ATTACK-Python-Client#53]
When running code in the provided ATT&CK-Data-Sources notebook, I receive an AttributeError - it appears that there is no remove_revoked attribute.

```
attack = get_attack_dataframe()
attack.head()
```

```
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_31480\3093517341.py in <module>
      1 import os
      2 os.environ["REQUESTS_CA_BUNDLE"] = r"c:\root.cer"
----> 3 attack = get_attack_dataframe()
      4 attack.head()

c:\mitre\repos\attack-datasources\docs\scripts\notebook_functions.py in get_attack_dataframe(matrix)
     49     if  (matrix.lower() == 'enterprise'):
     50         # Getting ATT&CK techniques
---> 51         attck = get_attck_from_stix(matrix = matrix)
     52         # Generating a dataframe with information collected
     53         attck = json_normalize(attck)

c:\mitre\repos\attack-datasources\docs\scripts\notebook_functions.py in get_attck_from_stix(matrix)
     38         attck = lift.get_enterprise_techniques(stix_format = False)
     39         # Removing revoked techniques
---> 40         attck = lift.remove_revoked(attck)
     41         return attck
     42     else:

AttributeError: 'attack_client' object has no attribute 'remove_revoked'
```

**Comment by Cyb3rWard0g** [comment]
Hello @pendraggon87 !

That notebook needs to be updated. We now remove revoked techniques by default

https://github.com/OTRF/ATTACK-Python-Client/blob/master/attackcti/attack_api.py#L342-L371

Specifically here:

https://github.com/OTRF/ATTACK-Python-Client/blob/master/attackcti/attack_api.py#L364

The new function is here:

https://github.com/OTRF/ATTACK-Python-Client/blob/8b49abd4d52a9505ebcaa51f25271132ad11fcc4/attackcti/attack_api.py#L283

I am submitting a PR in a few minutes to the following repo: https://github.com/mitre-attack/attack-datasources

BTW That is a repo we do not own or maintain.

**Comment by Cyb3rWard0g** [comment]
PR submitted but not action from external repo. closing this since it is not an issue with the library. Feel free to re-open this issue or reference it when the external repo is updated. Thank you @pendraggon87 !
