### ISSUE TITLE
Retrieving tactics from URL returns invalid JSON error

### ISSUE THREAD

**Issue by priceluke** [OTRF/ATTACK-Python-Client#54]
![image](https://user-images.githubusercontent.com/44372546/160439495-ad00ba09-1138-4b6d-b3b6-f4f90166cc44.png)

As title suggests, running:

```
!pip install attackcti
from attackcti import attack_client

lift = attack_client()
objs = lift.get_stix_objects()['enterprise']["tactics"]
```

returns:

```
JSONDecodeError: Unterminated string starting at: line 1 column 32259 (char 32258)

The above exception was the direct cause of the following exception:

InvalidJSONError                          Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/six.py in raise_from(value, from_value)

InvalidJSONError: Invalid JSON was received from https://cti-taxii.mitre.org/stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/objects/?match%5Btype%5D=attack-pattern
```

This is a new error as the same code was working a few days ago. May be endpoint related and not the fault of this repo - issue nonetheless.

**Comment by Spider2themax** [comment]
I didn't see this error when posting mine (very close time frame); this must definitely be a bug. I experienced similar but for `attack_client().get_techniques()` --> https://github.com/OTRF/ATTACK-Python-Client/issues/55

**Comment by Cyb3rWard0g** [comment]
Thank you @priceluke and @Spider2themax ! Testing right now.

**Comment by Cyb3rWard0g** [comment]
Hello @priceluke !

Would you mind trying again? I wonder if the issue was on the ATT&CK TAXII server? maybe. I do not get the same error with latest version

![image](https://user-images.githubusercontent.com/9653181/160538173-370d0a10-c2c6-4a5d-8865-f8c7a6e7d50c.png)

**Comment by Cyb3rWard0g** [comment]
Hello @Spider2themax !

Would you mind trying again? Similar to the previous message to Luke, I believe it might have been an issue with the TAXII server side:

![image](https://user-images.githubusercontent.com/9653181/160538345-cb38816c-f6bb-486a-93c0-d4a3f39ac683.png)

**Comment by priceluke** [comment]
Running again this morning and working fine. Must have been a server-side error. If I get a chance over the next few weeks I'll PR some error handling for this.

**Comment by Cyb3rWard0g** [comment]
Thank you @priceluke ! 🙏🏾
