### ISSUE TITLE
attack_client not workning (Err_connection)

### ISSUE THREAD

**Issue by mihaid-b** [OTRF/ATTACK-Python-Client#58]
Hello, upon running the examples from the site, I keep getting:

ConnectionError: HTTPSConnectionPool(host='cti-taxii.mitre.org', port=443): Max retries exceeded with url: /stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6d3c7c7350>: Failed to establish a new connection: [Errno 110] Connection timed out'

Accessing the above website via browser: cti-taxii.mitre.org took too long to respond.,

I suppose the server is down.

Anyone else facing this issue?

**Comment by Cyb3rWard0g** [comment]
Hello @mihaid-b !

It must have been the server down. It all seems to be working fine

<img width="826" alt="image" src="https://user-images.githubusercontent.com/9653181/177241106-a0664e8e-c766-4775-a30e-e56dbd29ba60.png">

Feel free to re-open this issue if you still have the same problems. We might have to open one on the ATT&CK side. 

Thank you for letting us know
