### ISSUE TITLE
How to Access the Cloud ATT&CK Matrix

### ISSUE THREAD

**Issue by flowtrader2016** [OTRF/ATTACK-Python-Client#68]
Hi, 

Is there any way to access and interact with the Cloud ATT&CK matrix using the ATTACK-Python-Client?  

Thanks

**Comment by Cyb3rWard0g** [comment]
Hey @flowtrader2016 !

You can use the "platform" properties of objects like techniques.

```python
>>> from attackcti.attack_api import attack_client
>>> lift = attack_client()
>>> 
>>> techniques = lift.get_techniques_by_platform("Azure AD")
>>> len(techniques)
50
>>> techniques[0]['name']
'Temporary Elevated Cloud Access'
>>> 
```

Platforms:

<img width="612" alt="image" src="https://github.com/OTRF/ATTACK-Python-Client/assets/9653181/34575d02-3dd6-4d66-82b4-abfc7f658eb1">
