### ISSUE TITLE
Expired certificate causes library crash

### ISSUE THREAD

**Issue by pllgiulio** [OTRF/ATTACK-Python-Client#70]
Hi all!
I was playing around with ATT&CK Python Client when I noticed an error due to the cti-taxii[.]mitre[.]org expired certificate.
I tried to contact MITRE ATT&CK but I did not receive any answer yet.
The library throw an exception since it can not verify the certificate validity
In case this is not the right channel for the notification, please tell me the proper way.
Kind regards,
Giulio

**Comment by Cyb3rWard0g** [comment]
Hey @pllgiulio! That would be the ATT&CK team.
