### ISSUE TITLE
Connection Timeout Issue When Using 'attackcti' Library

### ISSUE THREAD

**Issue by kanstat** [OTRF/ATTACK-Python-Client#71]
I am encountering a connection timeout issue while using the 'attackcti' library to interact with the Mitre ATT&CK data. The specific error is a TimeoutError that occurs when attempting to connect to the URL 'https://cti-taxii.mitre.org/stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/'. The connection timeout seems to be affecting the library's ability to retrieve the necessary data.
![attackctierror](https://github.com/OTRF/ATTACK-Python-Client/assets/86715068/3de513cf-05ac-4237-a32e-ab71b049d2c0)

**Comment by kanstat** [comment]
please give me solution asap.

**Comment by Cyb3rWard0g** [comment]
Hello! The ATT&CK TAXII Server sometimes goes down and there is not a way to know directly from their site. Sometimes connection gets refused after a period of time. That is outside of my control. Maybe we can have a way to retry or create additional checks.
